### ISSUE TITLE
repo: rename to openssh-keys?

### ISSUE THREAD

**Issue by lucab** [sdemos/ssh-keys#2]
I was confused at first, as the crate and repo names don't match. This propagates to most of the in-source docs/comments. To make it worse, an ssh-keys crates actually exists.

Did you settle on the `openssh-keys` name? If so, mind renaming the repository as well?

**Comment by sdemos** [comment]
good point. renamed it.

**Comment by lucab** [comment]
Turning travis on (if you didn't already) would also be good.

**Comment by sdemos** [comment]
Yeah, I turned on Travis and AppVeyor. Right now 32-bit gnu is failing,
because of some assembler error from rust-crypto.
